Выполнение ТЗ-11.
klv2503/java-filmorate pull request #2
Opened 2024-09-13 12:31 UTC by klv2503

Добавил нужные классы, в методах update подправил логику - сделал, чтобы корректные новые данные принимались, а некорректные игнорировались. Под изменения адаптировал тесты (новых не добавлял). Тесты, предложенные в ТЗ для проверки через postman, программа проходит

2024-09-14 15:21 UTC, db-exp requested changes

2024-09-14 15:21 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +    /*@AfterEach
удаляем старый код)

2024-09-14 15:21 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (isPositiveNumber(userId)) {
Positive аннотация на userId

2024-09-15 09:54 UTC, klv2503 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (isPositiveNumber(userId)) {
Это все от желания все самому контролировать. Пока не привык к тому, что очень много можно свалить на тот же Lombok или Spring...

2024-09-16 07:37 UTC, db-exp approved these changes

2024-09-16 07:37 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                if (!film.getReleaseDate().isBefore(cinemaBirthday)) {
можно и удобней вот так https://www.baeldung.com/spring-mvc-custom-validator

2024-09-20 07:10 UTC, merged