Выполнение ТЗ-12
klv2503/java-filmorate pull request #3
Opened 2024-10-16 13:42 UTC by klv2503

Реализована работа с БД. Ее проект в Readme. На всякий случай оставил реализацию InMemory, дополнив ее работой с новыми сущностями. Тесты InMemory убрал, тесты DB реализованы.

2024-10-17 09:55 UTC, db-exp requested changes

2024-10-17 09:55 UTC, db-exp commented on src/test/resources/schema.sql
> +              name varchar NOT NULL,
нужно везде проставить размерность varchar и это не всегда 255)

2024-10-17 09:55 UTC, db-exp commented on src/main/resources/schema.sql
> +              name varchar NOT NULL,
везде нужна размерность для varchar

2024-10-17 09:55 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Rating.java
> +    Long id;
private final

2024-10-17 09:55 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Rating.java
> +    String name;
private

2024-10-17 09:55 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmGenre.java
> +    Long id;
private модификаторы везде потеряны

2024-10-17 09:55 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dto/GenreRequest.java
> +    @NotBlank(message = "Признак жанра не может быть пустым.")
к NotBlank всегда можно Size добавлять

2024-10-17 09:55 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Gson gson = new Gson();
private final

2024-10-17 09:55 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dto/FilmRequest.java
> +    @NotNull(message = "Название фильма не может быть пустым")
NotNull и NotBlank можно не ставить вместе, лучше только NotBlank

2024-10-17 09:55 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
ну или вот так, где private не хватает

2024-10-17 09:55 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +
лишний отступ

2024-10-17 13:36 UTC, klv2503 commented on src/test/resources/schema.sql
> +              name varchar NOT NULL,
Ограничения на длину наименования жанров, рейтингов и фильмов указал исходя из самых длинных на сейчас. Description во всех случаях ограничил 200. Users трогать не стал - люди слишком изобретательны, самое длинное имя оказалось длиной под полторы тысячи букв. По итогам внес в Request'ы аннотации. Модификаторы указал, уже и сам какое-то время назад понял, что их расстановка у меня слабое место, пока не выправился. Модификаторы потребовали внести небольшие изменения в несколько классов. Тесты постмана проходятся.

2024-10-17 14:59 UTC, db-exp requested changes

2024-10-17 14:59 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dto/GenreRequest.java
> +    String name;
модификаторы доступа все еще отсутствуют)

2024-10-17 14:59 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dal/mappers/RatingRowMapper.java
> +    Long id;
модификаторы доступа все еще отсутствуют)

2024-10-17 14:59 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dto/FilmDto.java
> +    Long id;
модификаторы доступа все еще отсутствуют)

2024-10-17 14:59 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dto/UserRequest.java
> +    Long id;
модификаторы доступа все еще отсутствуют)

2024-10-17 14:59 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      Long id;
модификаторы доступа все еще отсутствуют)

2024-10-17 14:59 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      Long id; // уникальный идентификатор пользователя,
модификаторы доступа все еще отсутствуют)

2024-10-17 14:59 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmGenre/InMemoryFilmGenreStorage.java
> +    Map<Long, FilmGenre> filmGenres = new HashMap<>();
модификаторы доступа все еще отсутствуют)

2024-10-17 14:59 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/rating/InMemoryRatingStorage.java
> +    Map<Long, Rating> ratingMap = new HashMap<>();
модификаторы доступа все еще отсутствуют)

2024-10-17 14:59 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/FilmDbFilmoRateApplicationTests.java
> +    FilmRequest standartFilm = new FilmRequest("Halloween", "Classic horror",
модификаторы доступа все еще отсутствуют)

2024-10-17 14:59 UTC, db-exp commented on src/main/resources/schema.sql
> +              email varchar NOT NULL,
varchar без размерности - нужно проставить везде и в схеме тестов тоже

2024-10-17 14:59 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/UserDbFilmoRateApplicationTests.java
> +    User standartUser1 = new User("first@error.com", "firstLogin", "NameTest1",
нет модификатора доступа

2024-10-17 14:59 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/UserDbFilmoRateApplicationTests.java
> +    User standartUser2 = new User("second@error.com", "secondLogin", "NameTest2",
нет модификатора доступа

2024-10-17 14:59 UTC, db-exp commented on src/test/resources/schema.sql
> +              name varchar NOT NULL,
по правилам ревью - везде должна быть размерность для varchar

2024-10-17 16:26 UTC, klv2503 commented on src/test/resources/schema.sql
> +              name varchar NOT NULL,
Если я правильно понял, длина email может быть (по разным данным) 254 или 256 символов. Решил ограничиться чем-то разумным. Также ограничился более-менее разумной длиной логина. Что касается длины имени. Оказалось, что полное имя Пикассо на русском записывается строкой в 155 символов (на испанском короче, но не сильно). Ну я и поставил с запасом, кто их, этих испанцев знает... Не ставить же полторы тысячи.

2024-10-18 12:48 UTC, db-exp approved these changes

2024-10-20 10:11 UTC, merged